### ISSUE TITLE
Dark schema default content block needs lighter border color

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-longyearbyen#107]
Front page section blocks.

* [ ] empty content block need lighter border color if background color is dark

![screen shot 2017-01-06 at 13 05 51](https://cloud.githubusercontent.com/assets/13623224/21716196/a8e6327a-d411-11e6-8584-6338f9d8ba98.png)

**Comment by kaspar-naaber** [comment]
We decided to remove this automated color magic from our templates so we will not fix it at the moment. :)
