### ISSUE TITLE
Center and right aligned lists look ugly.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#39]
![screenshot 2016-11-15 16 12 51](https://cloud.githubusercontent.com/assets/3191867/20308902/7ed1c666-ab4e-11e6-927d-c4d574e1789b.png)

![screenshot 2016-11-15 16 16 57](https://cloud.githubusercontent.com/assets/3191867/20309000/f4ad6ad4-ab4e-11e6-82d1-73369c04c23d.png)

There are 2 possible options:

- [ ] Force them to allways align to left
or
- [x] Use `list-style-positioning: inside;` to align list item indicator with the content:

![screenshot 2016-11-15 16 15 09](https://cloud.githubusercontent.com/assets/3191867/20308970/d62840d4-ab4e-11e6-93b9-f98cff6798a9.png)

![screenshot 2016-11-15 16 17 27](https://cloud.githubusercontent.com/assets/3191867/20309016/04e5a060-ab4f-11e6-8bae-e90d56fe6f48.png)

**Comment by SSirjes** [comment]
I used list-style-positioning: inside;
