### ISSUE TITLE
"Front page" content area gallery slider empty image title is visible.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#51]
In editmode the title box is visible even if it is empty.

![screenshot 2016-12-01 10 21 59](https://cloud.githubusercontent.com/assets/3191867/20786683/26d39f2a-b7b0-11e6-8bbd-b3d404c23118.png)

**Comment by SSirjes** [comment]
Write photo title, save. 
Then delete added title, save. 
In edit mode, photo title's white box stays.
After refresh it will disappear. Video, what happens: http://recordit.co/q2XwNP9xhq

**Comment by kaspar-naaber** [comment]
Will be fixed from CMS side.
