### ISSUE TITLE
"Front page" content area gallery slider has few pixels of whitespace.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#52]
Fix only if it can be fixed easily!

**Editmode**

![screenshot 2016-12-01 10 24 16](https://cloud.githubusercontent.com/assets/3191867/20786716/54725124-b7b0-11e6-9d33-35d174ab5cfb.png)

**Live**

![screenshot 2016-12-01 10 24 36](https://cloud.githubusercontent.com/assets/3191867/20786727/60a1559e-b7b0-11e6-90f5-dac23781b952.png)

**Comment by SSirjes** [comment]
If there is this rule, then content block hover is not visible.
Video: http://recordit.co/L8FnjMXLfy

**Comment by SSirjes** [comment]
Reverting previous commit, where front page content area gallery slider had few pixels of whitespace.

_If any client needs that, then we will look at this issue again but at the moment it is a wontfix._
