### ISSUE TITLE
Language flags are misaligned:

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#59]
![screenshot 2016-12-01 11 14 37](https://cloud.githubusercontent.com/assets/3191867/20788013/7e5b7dce-b7b7-11e6-9b33-60f78af9fc53.png)

**Comment by SSirjes** [comment]
Language menu now. Is this better?

![screen shot 2016-12-07 at 20 09 28](https://cloud.githubusercontent.com/assets/13623224/20980448/3bd0755c-bcb9-11e6-92d2-9882ead352c9.png)
