### ISSUE TITLE
"Front page" feature box title doesn't look as designed.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#62]
If I put `<h1>` tag with the same text as in design to the left section, it doesn't look the same.

**Website**

![screenshot 2016-12-02 09 37 12](https://cloud.githubusercontent.com/assets/3191867/20826404/436ec786-b873-11e6-98f1-6391936b5225.png)

**Design**

![screenshot 2016-12-02 09 39 58](https://cloud.githubusercontent.com/assets/3191867/20826412/4d4b41bc-b873-11e6-93f1-ac6d5e21a0f4.png)

- [x] Check font color
- [ ] Try reducing `letter-spacing` or `font-size` to fit **"for modern living."** to one line.

**Comment by SSirjes** [comment]
* [ ] Color, font-size correction for headings.

Comment: In preview mode is feature box title on same row. 
Should it be on same row aslo in edit mode?
