### ISSUE TITLE
Main content area padding is too large.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#64]
In the design file the padding is couple of pixels smaller:

**Website**

![screenshot 2016-12-02 10 53 37](https://cloud.githubusercontent.com/assets/3191867/20827972/da11ce5e-b87d-11e6-93a4-0569e8118eb6.png)

**Design**

![screenshot 2016-12-02 10 52 44](https://cloud.githubusercontent.com/assets/3191867/20827975/ddc49932-b87d-11e6-8633-909ff9f13afd.png)

**Comment by SSirjes** [comment]
_Comment: in design blog and common page content paddigs are different.
Was decided, that blog and common page get same padding number (80px)._
