### ISSUE TITLE
Blog listing view paddings don't match with design.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#65]
Check these whitspacings:

![screenshot 2016-12-02 10 59 46](https://cloud.githubusercontent.com/assets/3191867/20828139/b2b3ee86-b87e-11e6-99d1-cf8276929626.png)

**Comment by SSirjes** [comment]
Blog post title, date and excerpt padding is now same as it is in design.
Padding between tags and blog post title is correct and approved with designer.
