### ISSUE TITLE
Bg picker automated color detection is still in use.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#71]
@hennrunnel – What was the final decision? Are we going to drop it in this template to add better support for **Design Editor** tool? If the _"magic"_ remains then the **Design Editor** must use the "for dark scheme" and "for light scheme" controllers like in some of the previous templates:

![dec-16-2016 12-23-08](https://cloud.githubusercontent.com/assets/3191867/21259603/d316cee8-c38a-11e6-84f5-e6b2070f1840.gif)

**Comment by SSirjes** [comment]
_Comment by @SSirjes: last decision was, that bg picker automated color detection don't come to Longyearbyen.
It should remove from code._
