### ISSUE TITLE
Bind Design Editor.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#77]
Add Design Editor functionality to modify standard template.

**Comment by kaspar-naaber** [comment]
#80 and #81 should be done before binding the Design Editor.
Let's make it clean this time:
- [ ] All CSS declarations that are overwritten by design editor should be removed from main CSS files.

**Comment by kaspar-naaber** [comment]
# Test round 1 results

- [ ] Font changes doesn't apply to headings: https://www.opentest.co/share/97ed2670d96311e6a7cb6f2926412bab

**Comment by kaspar-naaber** [comment]
# Test round 2 results

**Note: Most of these listed tasks are just my opinon and due to that, they are negotiable. Feel free to leave a comment under a specific item if you tend to disagree.**

---

- [ ] Under **"Blog article"** pages there is neve a **"Sub menu"**. It makes sense to not display that in the **"Blog article** layout.

**Comment by SSirjes** [comment]
# Test round 3 results

* [ ] If under '**Main styles**' secondary color is dark, then link hover text is dark and text readability is bad. 
**Edge case or we should fix this?**

![screen shot 2017-01-18 at 13 19 15](https://cloud.githubusercontent.com/assets/13623224/22062100/c9b60ff2-dd80-11e6-9211-07d7d6316820.png)
